### ISSUE TITLE
Views open in Selection mode by default, intead of Default 3D/Linked Cursor Control

### ISSUE THREAD

**Issue by ylep** [brainvisa/anatomist-free#20]
Anatomist views are opened in *Selection* mode instead of *Default 3D / Linked Cursor Control* mode.

Happens in a casa-distro 3 environment (`brainvisa-dev-ubuntu-18.04`)

**Comment by ylep** [comment]
@denisri was this an intentional change? It was very confusing at first for an experienced Anatomist user like me. Also it does not make a lot of sense to be in *Selection* mode when you are viewing a Volume.

**Comment by denisri** [comment]
No, this is not intentional at all, but there has actually been a change in Anatomist controls, but this is not what was expected...
I have added a new control with higher priority, which should thus be actve by default, providing the most common functionalities with the left mouse button or a touch device. Maybe there was a problem somewhere there. I'll check.

**Comment by denisri** [comment]
I could reproduce the problem, but in a casa-distro container which had previously been used to *install* programs (there were things in `/casa/install`). Once `/casa/install/*` have been removed, things came back to the expected behaviour.
Can it be your situation ?
This brings attention to another problem: once the software has been installed, they are first in the `PATH`s, and later modifs on the dev side are not taken into account... (I open a ticket in casa-distro).

**Comment by denisri** [comment]
see also brainvisa/casa-distro#150.

**Comment by ylep** [comment]
> I could reproduce the problem, but in a casa-distro container which had previously used to _install_ programs (there were things in `/casa/install`). Once `/casa/install/*` have been removed, things came back to the expected behaviour.
> Can it be your situation ?

No, it is not the case in my environment: `/casa/host/install` does not even exist. Still, I get the *Selection* tool activated by default.

**Comment by ylep** [comment]
For the record, here is my `bv_maker status`:

```
     master (ca540795) U=  anatomist/anatomist-free/master
     master (9727da1b) U=  axon/master
     master (d782da8)  U=  morphologist/morpho-deepsulci/master
   % master (e033477)  U=  capsul/master
     master (450fb1c)  U=  aims/aims-gpl/master
   % master (4d62414)  U=  anatomist/anatomist-gpl/master
     master (8d2b0b2)  U=  development/casa-distro/master
     master (a0bec0b)  U=  development/brainvisa-installer/master
     master (cb46dba)  U=  populse/populse_db/master
     master (ba6fcad)  U=  highres-cortex/master
     master (b1a89f1)  U=  aims/aims-til/master
     master (b946002)  U=  brainvisa-share/master
     master (87e56d6d) U=  aims/aims-free/master
     master (25aee97)  U=  development/brainvisa-release/master
     master (a122238)  U=  soma/soma-workflow/master
     master (6ed973e)  U=  soma/soma-base/master
     master (0ec7887)  U=  development/brainvisa-cmake/master
     master (57805ba)  U=  morphologist/morphologist-ui/master
     master (06d79df)  U=  soma/soma-io/master
*  % master (30ab666)  U=  disco/master
     master (ba6fcad)  U=  highres-cortex/master
```

**Comment by denisri** [comment]
In anatomist, could you please use the menu "_python / list loaded python modules_" and chek if you see the line:
```
  simple_controls : /casa/host/build/share/anatomist-4.6/python_plugins/simple_controls.pyc
```
If not, do you have the file `/casa/host/src/anatomist/anatomist-free/master/shared/python_plugins/simple_controls.py` and is it correctly symlinked from `/casa/host/build/share/anatomist-4.6/python_plugins/simple_controls.py` ?

If still yas, there must be somethings that causes a problem when loading this module. In a `ipython2 --gui=qt`shell (or shel opened from anatomist GUI), type:
```
import anatomist.api as ana
a = ana.Anatomist()
import simple_controls
print(simple_controls.__file__)
```
If there is an error, especially in the line `import simple_controls`, please copy it here.
If not, things should be working ! :S

**Comment by ylep** [comment]
I do have the `simple_controls` line, and it does not make any error when I load it from the Qtconsole in Anatomist :confused:

```
In [1]: import anatomist.api as ana
   ...: a = ana.Anatomist()
   ...: import simple_controls
   ...: print(simple_controls.__file__)
   ...: 
   ...: 
/casa/host/build/share/anatomist-4.6/python_plugins/simple_controls.pyc
```

Still, views open in *Selection* mode by default :confused:

**Comment by denisri** [comment]
And is the new control icon (with both a rotating sphere and a selection cursor on it) visible in the available controls list on the left of the window ?
Controls have a "priority" that allows to place / select them first or further in the controls list. Either there is a bug in selecting the highest priority here, or several controls do actually have the same priority, maybe I missed one of them.

**Comment by denisri** [comment]
I don't see another control with the same priority as the new one (4), anyway the selection control is later (8) and the former default one should appear before it (6).
So something has to force it somewhere.

**Comment by ylep** [comment]
The new control icon is indeed here, this is really strange. I just ran `bv_maker` and it still happens. I will try to investigate further when I have time.

**Comment by denisri** [comment]
If you can show me, it might help. But I think we have to add some prints in the code when controls are activated to understand when / from where this control is apparently forced. Formerly the "default 3D control" was forced from the view itself when it was created, but this was not a good thing (because it forbid to change the default control) and I removed this forcing code. But it doesn't explain why the selection one gets forced now instead of letting the priority work, and why I don't get the same behaviour as you get.

**Comment by denisri** [comment]
I have added a pair of functions in the C++/python bindings to allow debugging the controls system. Can you please update / recompile anatomist/pyanatomist, then run the following python script (after replacing the `image_filename` value with any image you have somewhere, and report the outputs here ?
```
import anatomist.api as ana
from soma.qt_gui.qt_backend import Qt
from pprint import pprint
from functools import partial

def print_controls(w, when):
    print(when)
    print('active control:', w.view().controlSwitch().activeControl())
    print('available:')
    pprint(w.view().controlSwitch().availableControls(), indent=4)
    print('activable:')
    pprint(w.view().controlSwitch().activableControls(), indent=4)

image_filename = '/home/someone/data/image.nii'

app = Qt.QApplication.instance()
a = ana.Anatomist()

w = a.createWindow('Axial')

print_controls(w, '--- before displaying object: ---')

vol = a.loadObject(image_filename)
w.addObjects(vol)

print_controls(w, '--- after displaying object: ---')

Qt.QTimer.singleShot(100, partial(print_controls, w,
                                  '--- after some event processing ---'))

if not app:
    app = Qt.QApplication.instance()
    app.exec_()
```
To compare with, my output (I just keep the interesting parts) is:
```
[ ...anatomist init output... ]
--- before displaying object: ---
active control: Left3DControl
available:
{   4: 'Left3DControl',
    6: 'Default 3D control',
    7: 'ObliqueControl',
    8: 'SelectionControl',
    9: 'Flight control',
    11: 'TransformControl',
    30: 'SmallBrainsControl',
    150: 'SplitFoldControl'}
activable:
{   4: 'Left3DControl',
    6: 'Default 3D control',
    7: 'ObliqueControl',
    8: 'SelectionControl',
    9: 'Flight control',
    11: 'TransformControl',
    30: 'SmallBrainsControl',
    150: 'SplitFoldControl'}
--- after displaying object: ---
active control: Left3DControl
available:
{   4: 'Left3DControl',
    6: 'Default 3D control',
    7: 'ObliqueControl',
    8: 'SelectionControl',
    9: 'Flight control',
    11: 'TransformControl',
    30: 'SmallBrainsControl',
    150: 'SplitFoldControl'}
activable:
{   4: 'Left3DControl',
    6: 'Default 3D control',
    7: 'ObliqueControl',
    8: 'SelectionControl',
    9: 'Flight control',
    11: 'TransformControl',
    30: 'SmallBrainsControl',
    150: 'SplitFoldControl'}
[ ...window init ouput... ]
--- after some event processing ---
active control: Left3DControl
available:
{   4: 'Left3DControl',
    6: 'Default 3D control',
    7: 'ObliqueControl',
    8: 'SelectionControl',
    9: 'Flight control',
    11: 'TransformControl',
    30: 'SmallBrainsControl',
    102: 'PaintControl',
    103: 'ConnectivityThresholdControl',
    106: 'DynSegmentControl',
    110: 'LabelNamingControl',
    150: 'SplitFoldControl'}
activable:
{   4: 'Left3DControl',
    6: 'Default 3D control',
    7: 'ObliqueControl',
    8: 'SelectionControl',
    9: 'Flight control',
    11: 'TransformControl',
    30: 'SmallBrainsControl',
    102: 'PaintControl',
    103: 'ConnectivityThresholdControl',
    106: 'DynSegmentControl',
    110: 'LabelNamingControl',
    150: 'SplitFoldControl'}
```

**Comment by ylep** [comment]
@denisri Here is the output of your script, in my casa-distro build that exhibits this issue.

```
--- before displaying object: ---
('active control:', 'SelectionControl')
available:
{   3: 'SelectionControl',
    6: 'Flight control',
    7: 'Left3DControl',
    8: 'Default 3D control',
    9: 'ObliqueControl',
    11: 'TransformControl',
    150: 'SplitFoldControl'}
activable:
{   3: 'SelectionControl',
    6: 'Flight control',
    7: 'Left3DControl',
    8: 'Default 3D control',
    9: 'ObliqueControl',
    11: 'TransformControl',
    150: 'SplitFoldControl'}
--- after displaying object: ---
('active control:', 'SelectionControl')
available:
{   3: 'SelectionControl',
    6: 'Flight control',
    7: 'Left3DControl',
    8: 'Default 3D control',
    9: 'ObliqueControl',
    11: 'TransformControl',
    150: 'SplitFoldControl'}
activable:
{   3: 'SelectionControl',
    6: 'Flight control',
    7: 'Left3DControl',
    8: 'Default 3D control',
    9: 'ObliqueControl',
    11: 'TransformControl',
    150: 'SplitFoldControl'}
```

```
--- after some event processing ---
('active control:', 'SelectionControl')
available:
{   3: 'SelectionControl',
    6: 'Flight control',
    7: 'Left3DControl',
    8: 'Default 3D control',
    9: 'ObliqueControl',
    11: 'TransformControl',
    102: 'PaintControl',
    103: 'ConnectivityThresholdControl',
    106: 'DynSegmentControl',
    110: 'LabelNamingControl',
    150: 'SplitFoldControl'}
activable:
{   3: 'SelectionControl',
    6: 'Flight control',
    7: 'Left3DControl',
    8: 'Default 3D control',
    9: 'ObliqueControl',
    11: 'TransformControl',
    102: 'PaintControl',
    103: 'ConnectivityThresholdControl',
    106: 'DynSegmentControl',
    110: 'LabelNamingControl',
    150: 'SplitFoldControl'}
```

**Comment by denisri** [comment]
The controls priority levels are not the same, that's why the selected one is not the same - I'll check that...

**Comment by denisri** [comment]
OK I have changed all priorities (increased them all to leave more room for higher priorities (lower numbers)) and to avoid possible conflicts. Can you update / rebuild and try again please ?

**Comment by ylep** [comment]
Thanks, the issue is fixed for me. Here is the new log for the record:

```
--- before displaying object: ---
('active control:', 'Default 3D control')
available:
{   1: 'Default 3D control',
    3: 'ObliqueControl',
    4: 'Flight control',
    6: 'SelectionControl',
    10: 'TransformControl',
    80: 'Left3DControl',
    8543: 'SplitFoldControl'}
activable:
{   1: 'Default 3D control',
    3: 'ObliqueControl',
    4: 'Flight control',
    6: 'SelectionControl',
    10: 'TransformControl',
    80: 'Left3DControl',
    8543: 'SplitFoldControl'}
--- after displaying object: ---
('active control:', 'Default 3D control')
available:
{   1: 'Default 3D control',
    3: 'ObliqueControl',
    4: 'Flight control',
    6: 'SelectionControl',
    10: 'TransformControl',
    80: 'Left3DControl',
    8543: 'SplitFoldControl'}
activable:
{   1: 'Default 3D control',
    3: 'ObliqueControl',
    4: 'Flight control',
    6: 'SelectionControl',
    10: 'TransformControl',
    80: 'Left3DControl',
    8543: 'SplitFoldControl'}
```

```
--- after some event processing ---
('active control:', 'Default 3D control')
available:
{   1: 'Default 3D control',
    3: 'ObliqueControl',
    4: 'Flight control',
    6: 'SelectionControl',
    10: 'TransformControl',
    80: 'Left3DControl',
    102: 'PaintControl',
    103: 'ConnectivityThresholdControl',
    106: 'DynSegmentControl',
    110: 'LabelNamingControl',
    8543: 'SplitFoldControl'}
activable:
{   1: 'Default 3D control',
    3: 'ObliqueControl',
    4: 'Flight control',
    6: 'SelectionControl',
    10: 'TransformControl',
    80: 'Left3DControl',
    102: 'PaintControl',
    103: 'ConnectivityThresholdControl',
    106: 'DynSegmentControl',
    110: 'LabelNamingControl',
    8543: 'SplitFoldControl'}
```

I will let you remove the debug prints and close the bug.

**Comment by ylep** [comment]
My previous message was after updating the sources but I had not recompiled. After running a full `bv_maker` I get the values below:

```
--- before displaying object: ---
('active control:', 'Left3DControl')
available:
{   80: 'Left3DControl',
    100: 'Default 3D control',
    201: 'SelectionControl',
    300: 'ObliqueControl',
    8543: 'SplitFoldControl',
    10000: 'TransformControl',
    400000: 'Flight control'}
activable:
{   80: 'Left3DControl',
    100: 'Default 3D control',
    201: 'SelectionControl',
    300: 'ObliqueControl',
    8543: 'SplitFoldControl',
    10000: 'TransformControl',
    400000: 'Flight control'}
--- after displaying object: ---
('active control:', 'Left3DControl')
available:
{   80: 'Left3DControl',
    100: 'Default 3D control',
    201: 'SelectionControl',
    300: 'ObliqueControl',
    8543: 'SplitFoldControl',
    10000: 'TransformControl',
    400000: 'Flight control'}
activable:
{   80: 'Left3DControl',
    100: 'Default 3D control',
    201: 'SelectionControl',
    300: 'ObliqueControl',
    8543: 'SplitFoldControl',
    10000: 'TransformControl',
    400000: 'Flight control'}
```

```
--- after some event processing ---
('active control:', 'Left3DControl')
available:
{   80: 'Left3DControl',
    100: 'Default 3D control',
    201: 'SelectionControl',
    300: 'ObliqueControl',
    893: 'PaintControl',
    8543: 'SplitFoldControl',
    9343: 'ConnectivityThresholdControl',
    10000: 'TransformControl',
    81023: 'LabelNamingControl',
    106576: 'DynSegmentControl',
    400000: 'Flight control'}
activable:
{   80: 'Left3DControl',
    100: 'Default 3D control',
    201: 'SelectionControl',
    300: 'ObliqueControl',
    893: 'PaintControl',
    8543: 'SplitFoldControl',
    9343: 'ConnectivityThresholdControl',
    10000: 'TransformControl',
    81023: 'LabelNamingControl',
    106576: 'DynSegmentControl',
    400000: 'Flight control'}
```

Anyway, the issue is fixed for me, thanks! I will let you close the bug.

**Comment by ylep** [comment]
Just to be sure, the tool that is now active by default is *not* the *Default 3D / Linked Cursor control*, but a (new?) tool named *Selection* (see below).

![Capture du 2020-12-02 15-02-03](https://user-images.githubusercontent.com/5501307/100882373-68606100-34af-11eb-8f46-09af4e2c289b.png)

**Comment by denisri** [comment]
OK.
The tooltip has not been reworked, you're right. As the new control is based on the selection control class, it displays its "parent" help. I have to write another one. But technically the issue is solved. Good.
